export const searchItems = [
    { label: 'Women - Boardshorts' },
    { label: 'Women - Shirts' },
    { label: 'Women - Shorts' },
    { label: 'Women - Hoodies' },
    { label: 'Women - Footwear' },
    { label: 'Women - Hats' },
    { label: 'Women - Shades' },
    { label: 'Women - Wetsuits' },
    { label: 'Women - Shoes' },
    { label: 'Men - Boardshorts' },
    { label: 'Men - Shirts' },
    { label: 'Men - Shorts' },
    { label: 'Men - Hoodies' },
    { label: 'Men - Footwear' },
    { label: 'Men - Hats' },
    { label: 'Men - Shades' },
    { label: 'Men - Wetsuits' },
    { label: 'Men - Shoes' },
    { label: 'Surfboards - Shortboards' },
    { label: 'Surfboards - Longboards' },
    { label: 'Surfboards - Hybrids' },
    { label: 'Surfboards - Guns' },
    { label: 'Accessories - Leashes' },
    { label: 'Accessories - wax' },
    { label: 'Accessories - sunscreen' },
    { label: 'Accessories - fins' },
    { label: 'Accessories - ding repair' },
    { label: 'Accessories - rashguards' },
    { label: 'Accessories - earplugs' },
    { label: 'Accessories - tail pads' },
    { label: 'Accessories - helmets' },
    { label: 'Accessories - watches' },
    { label: 'Accessories - towels' },
    { label: 'Accessories - bags' },
];