export const searchItems = [
    { label: 'Womens - Swimsuits' },
    { label: 'Womens - Tops' },
    { label: 'Womens - Hoodies' },
    { label: 'Womens - Footwear' },
    { label: 'Womens - Hats' },
    { label: 'Womens - Shades' },
    { label: 'Womens - Wetsuits' },
    { label: 'Mens - Boardshorts' },
    { label: 'Mens - Shirts' },
    { label: 'Mens - Shorts' },
    { label: 'Mens - Hoodies' },
    { label: 'Mens - Footwear' },
    { label: 'Mens - Hats' },
    { label: 'Mens - Shades' },
    { label: 'Mens - Wetsuits' },
    { label: 'Mens - Shoes' },
    { label: 'Surfboards - Shortboards' },
    { label: 'Surfboards - Longboards' },
    { label: 'Surfboards - Hybrids' },
    { label: 'Surfboards - Guns' },
    { label: 'Accessories - Leashes' },
    { label: 'Accessories - wax' },
    { label: 'Accessories - sunscreen' },
    { label: 'Accessories - fins' },
    { label: 'Accessories - ding repair' },
    { label: 'Accessories - rashguards' },
    { label: 'Accessories - earplugs' },
    { label: 'Accessories - tail pads' },
    { label: 'Accessories - helmets' },
    { label: 'Accessories - watches' },
    { label: 'Accessories - towels' },
    { label: 'Accessories - bags' },
];